[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "plotly>=6.1.2",
    "psycopg[binary]>=3.2.0",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.45.1",
]
